### ISSUE TITLE
distinuere riduzione/vista nei compiti ridotti

### ISSUE THREAD

**Issue by SoftwareIISGubbio** [SoftwareIISGubbio/testBuilder#1]
Il programma offre la possibilità di generare compoiti ridotti e di generare compiti con le risposte su diverse righe.

sarebbe utile avere la possibilità di generare compiti ridotti **e/o** con le risposte su diverse righe

**Comment by edoardoIISGubbio** [comment]
la versione 1.4 lo fa a25254d8955e6fbfbc0aad79b77fe653828b676b
